### ISSUE TITLE
Presto 0.93 and 0.96 compilation errors

### ISSUE THREAD

**Issue by mfirry** [airbnb/airpal#99]
If I do not specify any prestoVersion it works just fine.
When I do specify (I've just tried with 0.93 and 0.96) I get compilation errors.

See: https://gist.github.com/mfirry/492a502fa4b1a4246bfe

java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

**Comment by andykram** [comment]
Looks like there were some changes to the internals since the latest version I've tested (0.87 or so, I believe). We're waiting to do a full upgrade of Airpal to comply with the latest Presto internals until the newest version of Dropwizard is released. The reasoning here is that Presto has upgraded to Jersey 2 (completely different API and set of dependencies), whereas stable Dropwizard is on Jersey 1. Hopefully Dropwizard 0.8 (with Jersey 2) is released in the next couple of weeks and we can move forward with the upgrade.

One positive thing to note here however, is that the Presto HTTP API has done a very good job of maintaining backwards compatibility. We've been able to compile Airpal against older versions of Presto and have it successfully query newer versions of Presto.

**Comment by mfirry** [comment]
Alright. Thanks so much for your support. Will wait for a little before trying Airpal then.

**Comment by jamestyack** [comment]
Ditto.. and I ran against Presto 0.98 successfully after using default version at build.

**Comment by grepwood** [comment]
The same happens with Presto 0.100

**Comment by xuhaibo** [comment]
The same happens with Presto 0.109

**Comment by juanpampliega** [comment]
Any updates on compatibility for newer versions of Presto?

**Comment by grepwood** [comment]
@juanpampliega judging from the last 4 commits, not at all.

**Comment by XiLongZheng** [comment]
@andykram any plan to get this fixed?

**Comment by mkanchwala** [comment]
Can we also add 0.110 in the Compatibility list.

Thanks

**Comment by jprosevear** [comment]
Seems to work with 0.115

**Comment by erikdubbelboer** [comment]
@andykram I'm guessing airbnb is still using Presto 0.87 (which is over a year old)? So we shouldn't expect airbnb to fix this issue?

**Comment by mmacny** [comment]
@andykram can you provide an update on this? Still failing when installing latest builds

**Comment by mfirry** [comment]
I'm now trying Presto 0.149 and still have issues (http://pastie.org/10901705).
